import { Workflow } from '../../types/workflow';
import { ProviderType } from '../../types/skill';
import { PROVIDERS } from '../../types/provider';

export interface GeneratedOutput {
  providerId: ProviderType;
  providerName: string;
  formattedPrompt: string;
  markdownExport: string;
  jsonExport: string;
  generatedAt: string;
}

export class ProviderAdapterEngine {
  static adaptWorkflow(workflow: Workflow, provider: ProviderType): GeneratedOutput {
    const enabledSteps = workflow.steps
      .filter((s) => s.enabled)
      .sort((a, b) => a.position - b.position);

    let formattedPrompt = '';

    switch (provider) {
      case 'claude':
        formattedPrompt = this.formatClaudeXml(workflow, enabledSteps);
        break;
      case 'gemini':
        formattedPrompt = this.formatGeminiSystemInstructions(workflow, enabledSteps);
        break;
      case 'gpt':
      default:
        formattedPrompt = this.formatGptMarkdownRole(workflow, enabledSteps);
        break;
    }

    const providerInfo = PROVIDERS[provider];

    const jsonExport = JSON.stringify(
      {
        workflowName: workflow.name,
        goal: workflow.goal,
        provider: providerInfo.name,
        model: providerInfo.modelIdentifier,
        generatedAt: new Date().toISOString(),
        steps: enabledSteps.map((s) => ({
          position: s.position,
          skillName: s.skill?.name,
          objective: s.skill?.objective,
          customInstructions: s.customInstructions || null,
        })),
        systemPromptPayload: formattedPrompt,
      },
      null,
      2
    );

    return {
      providerId: provider,
      providerName: providerInfo.name,
      formattedPrompt,
      markdownExport: formattedPrompt,
      jsonExport,
      generatedAt: new Date().toISOString(),
    };
  }

  private static formatClaudeXml(workflow: Workflow, steps: any[]): string {
    return `<system_instructions>
You are an expert AI assistant tasked with executing the following structured Veya Workflow.

<workflow_goal>
${workflow.goal}
</workflow_goal>

<execution_sequence>
${steps
  .map(
    (step) => `
<step index="${step.position}" skill="${step.skill?.name || 'Custom Step'}">
  <objective>${step.skill?.objective || ''}</objective>
  <custom_instructions>${step.customInstructions || 'None'}</custom_instructions>
  <instructions>
${step.skill?.instructions || ''}
  </instructions>
  <rules>
${(step.skill?.rules || []).map((r: string) => `    - ${r}`).join('\n')}
  </rules>
  <expected_output>${step.skill?.expected_output || ''}</expected_output>
</step>`
  )
  .join('\n')}
</execution_sequence>

<output_directive>
Execute each step in sequential order. Provide actionable code, documentation, and architecture diagrams for the user's target project.
</output_directive>
</system_instructions>`;
  }

  private static formatGeminiSystemInstructions(workflow: Workflow, steps: any[]): string {
    return `SYSTEM INSTRUCTION / CONTEXT BLOCK:

GOAL: ${workflow.goal}

WORKFLOW EXECUTION PIPELINE:
${steps
  .map(
    (step) => `
--- STEP ${step.position}: ${step.skill?.name || 'Custom Step'} ---
OBJECTIVE: ${step.skill?.objective || ''}
${step.customInstructions ? `CUSTOM OVERRIDE: ${step.customInstructions}` : ''}

INSTRUCTIONS:
${step.skill?.instructions || ''}

RULES & CONSTRAINTS:
${(step.skill?.rules || []).map((r: string) => `* ${r}`).join('\n')}

EXPECTED DELIVERABLE:
${step.skill?.expected_output || ''}
`
  )
  .join('\n')}

Execute sequentially according to Gemini multimodal and structured reasoning guidelines.`;
  }

  private static formatGptMarkdownRole(workflow: Workflow, steps: any[]): string {
    return `# SYSTEM ROLE: VEYA WORKFLOW ENGINE

## PRIMARY GOAL
${workflow.goal}

## WORKFLOW STEPS

${steps
  .map(
    (step) => `### Step ${step.position}: ${step.skill?.name || 'Custom Step'}
**Objective:** ${step.skill?.objective || ''}
${step.customInstructions ? `**Custom Context:** ${step.customInstructions}` : ''}

**Instructions:**
${step.skill?.instructions || ''}

**Rules:**
${(step.skill?.rules || []).map((r: string) => `- ${r}`).join('\n')}

**Expected Output:**
${step.skill?.expected_output || ''}
`
  )
  .join('\n\n')}

---
*Generated by Veya Universal AI Skill Engine for GPT-4o*`;
  }
}
