import { CanonicalSkill } from '../../types/skill';
import { Workflow } from '../../types/workflow';

export const SEED_SKILLS: CanonicalSkill[] = [
  {
    id: 'skill-rn-architecture',
    name: 'React Native Architecture',
    slug: 'react-native-architecture',
    description: 'Scalable React Native app structure with Expo Router & Zustand',
    objective: 'Architect clean cross-platform React Native mobile applications.',
    inputs: [{ name: 'userContext', description: 'Target app requirements', required: true }],
    prerequisites: ['Basic domain context'],
    instructions:
      '1. Review navigation structure using Expo Router.\n2. Set up Zustand store for state management.\n3. Implement dark/light theme tokens and reusable UI components.',
    steps: [
      { number: 1, title: 'Navigation Setup' },
      { number: 2, title: 'State & Theme Ingestion' },
      { number: 3, title: 'Component Composition' },
    ],
    rules: [
      'Use Expo Router for all screen routing',
      'Follow modern functional component hooks patterns',
      'Ensure cross-platform compatibility on iOS, Android, and Web',
    ],
    expected_output: 'Structured TypeScript React Native architecture blueprint.',
    visibility: 'public',
    version: 1,
    rating_average: 5.0,
    rating_count: 1,
    usage_count: 142,
    save_count: 38,
    security_scan_status: 'clean',
    security_scanned_at: new Date().toISOString(),
    category: 'Coding',
    tags: ['Coding', 'React Native', 'Expo', 'Mobile', 'TypeScript'],
    providerCompatibility: ['openrouter', 'gemini', 'claude', 'gpt'],
    source: { type: 'official', source_name: 'Veya Core' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'skill-prd-requirements',
    name: 'PRD Requirements Synthesizer',
    slug: 'prd-requirements-synthesizer',
    description: 'Transforms unstructured product goals into structured PRDs',
    objective: 'Generate comprehensive product requirements documents with user stories and MVP specs.',
    inputs: [{ name: 'userContext', description: 'Product goal idea', required: true }],
    prerequisites: ['Raw product idea or user goal'],
    instructions:
      '1. Extract core value proposition.\n2. Define functional requirements & user personas.\n3. Outline MVP scope and non-functional security/performance criteria.',
    steps: [
      { number: 1, title: 'Value Proposition Extraction' },
      { number: 2, title: 'Functional Spec Definition' },
      { number: 3, title: 'MVP Scope Boundaries' },
    ],
    rules: [
      'Keep MVP features strictly minimal and actionable',
      'Specify clear acceptance criteria for user stories',
    ],
    expected_output: 'Structured PRD document with executive summary and user stories.',
    visibility: 'public',
    version: 1,
    rating_average: 4.9,
    rating_count: 1,
    usage_count: 98,
    save_count: 24,
    security_scan_status: 'clean',
    security_scanned_at: new Date().toISOString(),
    category: 'Productivity',
    tags: ['Productivity', 'PRD', 'Product', 'Planning', 'MVP'],
    providerCompatibility: ['openrouter', 'gemini', 'claude', 'gpt'],
    source: { type: 'official', source_name: 'Veya Core' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'skill-saas-architecture',
    name: 'SaaS MVP & RLS Security Architect',
    slug: 'saas-architecture-rls',
    description: 'Full-stack SaaS architecture with Supabase RLS and Stripe billing',
    objective: 'Design secure multi-tenant SaaS backends with Row Level Security and Stripe webhooks.',
    inputs: [{ name: 'userContext', description: 'SaaS product schema', required: true }],
    prerequisites: ['Database schema or entity model'],
    instructions:
      '1. Define PostgreSQL schema with foreign key relationships.\n2. Write strict Row Level Security (RLS) policies for user data isolation.\n3. Configure Stripe webhook event handlers.',
    steps: [
      { number: 1, title: 'Schema Definition' },
      { number: 2, title: 'RLS Policy Engineering' },
      { number: 3, title: 'Stripe Billing Webhooks' },
    ],
    rules: [
      'Enable RLS on all Supabase tables by default',
      'Never expose secret keys in client-side code',
    ],
    expected_output: 'PostgreSQL SQL migrations and Supabase RLS policy scripts.',
    visibility: 'public',
    version: 1,
    rating_average: 4.8,
    rating_count: 1,
    usage_count: 85,
    save_count: 19,
    security_scan_status: 'clean',
    security_scanned_at: new Date().toISOString(),
    category: 'Business',
    tags: ['Business', 'SaaS', 'Supabase', 'Database', 'Stripe', 'RLS'],
    providerCompatibility: ['openrouter', 'gemini', 'claude', 'gpt'],
    source: { type: 'official', source_name: 'Veya Core' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const SEED_WORKFLOWS: Workflow[] = [
  {
    id: 'wf-ai-note-app',
    user_id: 'veya-core',
    name: 'AI Note-Taking Mobile App MVP',
    description: 'End-to-end workflow to plan, architect, and build an AI mobile app',
    goal: 'Build an AI-powered note-taking mobile app with audio transcription and automatic summary',
    provider_id: 'claude',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    steps: [
      {
        id: 'step-1',
        workflow_id: 'wf-ai-note-app',
        skill_id: 'skill-prd-requirements',
        position: 1,
        enabled: true,
        skill: SEED_SKILLS[1],
      },
      {
        id: 'step-2',
        workflow_id: 'wf-ai-note-app',
        skill_id: 'skill-rn-architecture',
        position: 2,
        enabled: true,
        skill: SEED_SKILLS[0],
      },
    ],
  },
];
